# A https://taskfile.dev (similar to Makefile)
version: "3"

tasks:
  full-build:
    deps: [build, licenses]

  preview:
    cmds:
      - task: build
      - bun run preview

  dev:
    cmds:
      - bun run dev

  build:
    cmds:
      - bun run build

  licenses:
    cmds:
      - cp .LICENSE.main LICENSE
      - bun run licenses generate-disclaimer >> LICENSE
      - bun run licenses list >> LICENSE

  upgrade:
    cmds:
      - npx @astrojs/upgrade
      - task: build
      - task: licenses
